version: "3.9" # Specify the Compose file format version

services:
  svelte-app-dev:
    build:
      context: . # Build context is the current directory
      dockerfile: Dockerfile
      target: development # Target the development stage
    ports:
      - "3500:3500"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./vite.config.ts:/app/vite.config.ts
      - ./svelte.config.js:/app/svelte.config.js

  svelte-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production # Target the production stage
    ports:
      - "8080:3000"
